### ISSUE TITLE
res folder is missing

### ISSUE THREAD

**Issue by DelphiWorlds** [Codrax/Bad-Apple-Windows#1]
As per title. Readme says "in the res folder", but there is none

**Comment by Codrax** [comment]
My bad. The "res" folder is in the release 1.0 zip file.
I forgot to add it to the source code. The folder also needs to be in the same directory as the executable.

I will add It a bit later, but meanwhile you can extract It from "BadAppleWin.zip".

Thanks for bringing this issue to my attention.
